ApiConstants = {
  RECEIVE_TASKS: "RECEIVE_TASKS",
  RECEIVE_ONE_TASK: "RECEIVE_ONE_TASK",
  RECEIVE_ALL_TEAM_USERS: "RECEIVE_ALL_TEAM_USERS",
  RECEIVE_ALL_PROJECTS: "RECEIVE_ALL_PROJECTS"
};

module.exports = ApiConstants;
